### ISSUE TITLE
Glitch: Searching movies triggers a lot of image requests

### ISSUE THREAD

**Issue by xaverlohmueller** [spacepandas/cineaste-ios#39]
## Description:

When searching for movies, a lot of image requests are triggered. This can look a little funky, esp. when using a slow internet connection:

![20180701_094840](https://user-images.githubusercontent.com/16212751/42132298-84197480-7d15-11e8-8459-2bdd5b0f1ac5.GIF)

**Comment by fbernutz** [comment]
Good idea! Feels a lot better now. 
The only thing I still think is not optimal, is when you have a search query and the results don't change (like when you are searching for `Harry Potter`), the images flicker because the `prepareForReuse` is called every time you add a letter and the images then reset to the placeholder image again. But there is no option to check if the `prepareForReuse` is really needed, is it? Do you have an idea how this could be solved?

![juli-01-2018 21-47-20](https://user-images.githubusercontent.com/26111180/42138109-68cd3096-7d78-11e8-9db1-6d6e9dfdf45d.gif)
